spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libro1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
server:
  servlet.encoding.charset: UTF-8
  servlet.encoding.force: true
  error:
    include-stacktrace: ALWAYS
    include-exception: false