spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libro1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: messenger.individuales@gmail.com
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false


server:
  servlet.encoding.charset: UTF-8
  servlet.encoding.force: true
  error:
    include-stacktrace: ALWAYS
    include-exception: false